<?php

namespace Database\Seeders;

use App\Domain\Courses\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title' => 'Экспресс-курс подготовки к родам',
                'slug' => 'ekspress-kurs-podgotovki-k-rodam',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Короткая очная программа для тех, кому нужно быстро собрать базу перед родами.',
                'price' => 7900,
                'duration_hours' => 6,
                'lessons_count' => 3,
                'badge' => 'Офлайн',
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Курс подготовки к родам за 3 часа',
                'slug' => 'kurs-podgotovki-k-rodam-za-3-chasa',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Интенсивная встреча с самым важным: этапы родов, дыхание, сборы и вопросы к врачу.',
                'price' => 8500,
                'duration_hours' => 3,
                'lessons_count' => 1,
                'badge' => 'Интенсив',
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'title' => 'Основной курс подготовки к родам',
                'slug' => 'osnovnoy-kurs-podgotovki-k-rodam',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Последовательная очная подготовка: роды, восстановление, партнёрская поддержка и первые дни с малышом.',
                'price' => 11900,
                'duration_hours' => 12,
                'lessons_count' => 6,
                'badge' => 'Хит',
                'is_featured' => true,
                'sort_order' => 30,
            ],
            [
                'title' => 'Индивидуальный экспресс-курс подготовки к родам',
                'slug' => 'individualnyy-ekspress-kurs-podgotovki-k-rodam',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Персональная встреча под вашу ситуацию, сроки беременности и вопросы семьи.',
                'price' => 17000,
                'duration_hours' => 5,
                'lessons_count' => 2,
                'badge' => '1:1',
                'is_featured' => false,
                'sort_order' => 40,
            ],
            [
                'title' => 'Индивидуальный основной курс подготовки к родам',
                'slug' => 'individualnyy-osnovnoy-kurs-podgotovki-k-rodam',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Расширенная индивидуальная программа с подробной подготовкой к родам и послеродовому периоду.',
                'price' => 25000,
                'duration_hours' => 10,
                'lessons_count' => 5,
                'badge' => '1:1',
                'is_featured' => false,
                'sort_order' => 50,
            ],
            [
                'title' => 'Рождение второго, третьего ребёнка',
                'slug' => 'rozhdenie-vtorogo-tretego-rebenka',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Подготовка для родителей, у которых уже есть опыт, но появились новые вопросы и ожидания.',
                'price' => 8500,
                'duration_hours' => 4,
                'lessons_count' => 2,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 60,
            ],
            [
                'title' => 'Если вам предстоит кесарево сечение',
                'slug' => 'esli-vam-predstoit-kesarevo-sechenie',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Как подготовиться к операции, восстановлению и первым часам рядом с ребёнком.',
                'price' => 5900,
                'duration_hours' => 3,
                'lessons_count' => 1,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 70,
            ],
            [
                'title' => 'Курсы по партнёрским родам',
                'slug' => 'kursy-po-partnerskim-rodam',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Семья и отношения',
                'short_desc' => 'Практика для пары: как поддерживать, что говорить и как действовать в разные периоды родов.',
                'price' => 8500,
                'duration_hours' => 4,
                'lessons_count' => 2,
                'badge' => 'Для пары',
                'is_featured' => true,
                'sort_order' => 80,
            ],
            [
                'title' => 'Я - папа',
                'slug' => 'ya-papa',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Семья и отношения',
                'short_desc' => 'Курс для будущих пап о поддержке, быте, участии в родах и первых неделях дома.',
                'price' => 8500,
                'duration_hours' => 4,
                'lessons_count' => 2,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 90,
            ],
            [
                'title' => 'Наши дети - близнецы',
                'slug' => 'nashi-deti-bliznetsy',
                'format' => Course::FORMAT_OFFLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Отдельная встреча для семей, которые ждут двойню и хотят заранее продумать уход и помощь.',
                'price' => 3600,
                'duration_hours' => 2,
                'lessons_count' => 1,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 100,
            ],
            [
                'title' => 'Плановое кесарево сечение: подготовка к родам',
                'slug' => 'planovoe-kesarevo-sechenie-podgotovka-k-rodam',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Онлайн-подготовка к плановой операции, восстановлению и спокойному старту материнства.',
                'price' => 2500,
                'duration_hours' => 3,
                'lessons_count' => 5,
                'badge' => 'Онлайн',
                'is_featured' => true,
                'sort_order' => 110,
            ],
            [
                'title' => 'Скоро папа!',
                'slug' => 'skoro-papa',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Семья и отношения',
                'short_desc' => 'Короткий онлайн-курс для будущего папы: как быть рядом и не теряться.',
                'price' => 590,
                'duration_hours' => 1,
                'lessons_count' => 3,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 120,
            ],
            [
                'title' => 'Второй ребёнок: подготовка к рождению',
                'slug' => 'vtoroy-rebenok-podgotovka-k-rozhdeniyu',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Как подготовить себя, старшего ребёнка и семейный быт к появлению малыша.',
                'price' => 590,
                'duration_hours' => 1,
                'lessons_count' => 3,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 130,
            ],
            [
                'title' => 'Онлайн-курс подготовки к родам',
                'slug' => 'onlayn-kurs-podgotovki-k-rodam',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Подготовка к родам',
                'short_desc' => 'Полная онлайн-программа для самостоятельной подготовки в удобном темпе.',
                'price' => 7500,
                'duration_hours' => 10,
                'lessons_count' => 12,
                'badge' => 'Хит',
                'is_featured' => true,
                'sort_order' => 140,
            ],
            [
                'title' => 'Истерика у ребёнка: как всем остаться целыми',
                'slug' => 'isterika-u-rebenka-kak-vsem-ostatsya-tselymi',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Развитие и воспитание',
                'short_desc' => 'Понятные шаги для родителей, когда эмоции ребёнка становятся слишком сильными.',
                'price' => 590,
                'duration_hours' => 1,
                'lessons_count' => 3,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 150,
            ],
            [
                'title' => 'Адаптация к детскому саду',
                'slug' => 'adaptatsiya-k-detskomu-sadu',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Развитие и воспитание',
                'short_desc' => 'Бесплатный курс о мягком входе в детский сад и снижении тревоги у всей семьи.',
                'price' => 0,
                'duration_hours' => 1,
                'lessons_count' => 3,
                'badge' => 'Бесплатно',
                'is_featured' => true,
                'sort_order' => 160,
            ],
            [
                'title' => 'Семья с особенным ребёнком',
                'slug' => 'semya-s-osobennym-rebenkom',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Семья и отношения',
                'short_desc' => 'Поддержка родителей, которым важно выстроить устойчивый и бережный семейный ритм.',
                'price' => 590,
                'duration_hours' => 1,
                'lessons_count' => 3,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 170,
            ],
            [
                'title' => 'Несколько детей в семье: от конфликтов к радости',
                'slug' => 'neskolko-detey-v-seme-ot-konfliktov-k-radosti',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Семья и отношения',
                'short_desc' => 'Как помогать детям договариваться, делить внимание родителей и оставаться командой.',
                'price' => 1290,
                'duration_hours' => 2,
                'lessons_count' => 4,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 180,
            ],
            [
                'title' => 'Детские прививки: что нужно знать родителям',
                'slug' => 'detskie-privivki-chto-nuzhno-znat-roditelyam',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Спокойный разбор базовых вопросов о вакцинации и подготовке к приёму у врача.',
                'price' => 490,
                'duration_hours' => 1,
                'lessons_count' => 2,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 190,
            ],
            [
                'title' => 'Завершаем грудное вскармливание',
                'slug' => 'zavershaem-grudnoe-vskarmlivanie',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Бережные сценарии завершения кормления с учётом ребёнка, мамы и семейного режима.',
                'price' => 1290,
                'duration_hours' => 2,
                'lessons_count' => 4,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 200,
            ],
            [
                'title' => 'Грудное вскармливание от А до Я',
                'slug' => 'grudnoe-vskarmlivanie-ot-a-do-ya',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Базовый курс о прикладывании, режиме, частых трудностях и поддержке лактации.',
                'price' => 2500,
                'duration_hours' => 4,
                'lessons_count' => 6,
                'badge' => 'Популярно',
                'is_featured' => true,
                'sort_order' => 210,
            ],
            [
                'title' => 'Совместный сон: за и против',
                'slug' => 'sovmestnyy-son-za-i-protiv',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Как принять решение о сне семьи и сделать выбранный формат безопаснее и спокойнее.',
                'price' => 1290,
                'duration_hours' => 2,
                'lessons_count' => 4,
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 220,
            ],
            [
                'title' => 'Уход за новорождённым',
                'slug' => 'uhod-za-novorozhdennym',
                'format' => Course::FORMAT_ONLINE,
                'category' => 'Уход за малышом',
                'short_desc' => 'Практичный курс о первых днях дома: гигиена, сон, кормление, сигналы нормы и тревоги.',
                'price' => 2500,
                'duration_hours' => 4,
                'lessons_count' => 6,
                'badge' => 'Новинка',
                'is_featured' => true,
                'sort_order' => 230,
            ],
        ];

        $slugs = array_column($courses, 'slug');

        Course::query()
            ->whereNotIn('slug', $slugs)
            ->update([
                'is_published' => false,
                'is_featured' => false,
            ]);

        foreach ($courses as $course) {
            $description = '<p>' . e($course['short_desc']) . '</p><p>Подробное описание программы будет добавлено после согласования финального списка курсов.</p>';
            $whatYouLearn = $this->learningPoints($course['format'], $course['category']);

            Course::updateOrCreate(
                ['slug' => $course['slug']],
                $course + [
                    'description' => $description,
                    'currency' => 'RUB',
                    'access_type' => ((float) $course['price']) <= 0 ? 'free' : 'lifetime',
                    'level' => 'beginner',
                    'what_you_learn' => $whatYouLearn,
                    'requirements' => ['Специальная подготовка не требуется'],
                    'includes' => [
                        $course['format'] === Course::FORMAT_OFFLINE ? 'Очная встреча' : 'Доступ к материалам курса',
                        'Практические рекомендации',
                        'Возможность задать вопросы перед записью',
                    ],
                    'is_active' => true,
                    'is_published' => true,
                    'status' => 'published',
                    'published_at' => now(),
                    'meta_title' => $course['title'] . ' — Школа материнства рожаем вместе',
                    'meta_description' => $course['short_desc'],
                ],
            );
        }
    }

    private function learningPoints(string $format, string $category): array
    {
        $base = [
            'Понятный план подготовки без лишней теории',
            'Практические шаги для семьи',
        ];

        $base[] = match ($category) {
            'Подготовка к родам' => 'Что важно обсудить и подготовить до родов',
            'Семья и отношения' => 'Как распределять роли и поддержку внутри семьи',
            'Развитие и воспитание' => 'Как спокойнее реагировать на сложные этапы развития ребёнка',
            default => 'Как ухаживать за малышом увереннее и спокойнее',
        };

        $base[] = $format === Course::FORMAT_OFFLINE
            ? 'Живое занятие с возможностью разобрать личные вопросы'
            : 'Материалы, к которым можно возвращаться в удобном темпе';

        return $base;
    }
}
